baseURL = "https://letstry.science"
languageCode = "en-us"
title = "Snippets of Nifty"
copyright = "Copyright © 2019-2020, Braxton Schafer"
theme = "npq-hugo"
pygmentsUseClasses=true

[params]
  author = "Braxton Schafer"
  description = "Snippets of Nifty"
  keywords = "tech howto guide woodworking music"
  useAvatar = false
  microBlogSection = "microposts"
  displayMicroBlog = true
  displayRecent = true
  recentMax = 4
  mail = "braxton@cmdcentral.xyz"

[menu]

  [[menu.main]]
    name = "Home"
    pre = "<i class='fas fa-home fa-sm'></i>"
    url = "/"
    weight = -9

  [[menu.main]]
    name = "Blog"
    pre = "<i class='fas fa-dumpster-fire'></i>"
    url = "/blog/"
    weight = -8

  [[menu.main]]
    name = "Tags"
    pre = "<i class='fas fa-tags fa-ms'></i>"
    url = "/tags/"
    weight = -7

  [[menu.main]]
    name = "About"
    pre = "<i class='fas fa-info'></i>"
    url = "/about/"
    weight = -6

  [[menu.main]]
    name = "GitLab"
    pre = "<i class='fab fa-gitlab'></i>"
    url = "https://gitlab.com/bjschafer"
    weight = -3

  [[menu.main]]
    name = "Twitter"
    pre = "<i class='fab fa-twitter'></i>"
    url = "https://twitter.com/bronxasaur"
    weight = -1

  [[menu.main]]
    name = "Portfolio"
    pre = "<i class='fas fa-briefcase'></i>"
    url = "https://bjschafer.com"
    weight = 110
