baseURL = "https://letstry.science/"
title = "Snippets of Nifty"
copyright = "Copyright © 2019, Braxton Schafer"
languageCode = "en-US"
theme = "indigo"

[params]
  Author = "Braxton Schafer"
  Description = "Woodworking, tech, infosec, etc."
  Subtitle = "Thoughts and things"
  Avatar = "images/site-logo.svg"
  Biography = "A short description, a few sentences describing the author. Set the 'ShowBio' parameter to false to hide this."
  ShowBio = false
  PermalinkText = "🔗"

  # Contact/social-network identifiers for social icons
  EmailAddress = "braxton@cmdcentral.xyz"
  GitHubUser = "bjschafer"
  GitLabUser = "bjschafer"
  KeybaseUser = "bjschafer"
  LinkedInUser = "bjschafer"
  RedditUser = "bronxasaur"
  StackOverflowUser = "bjschafer"
  TwitterUser = "bronxasaur"

  # These are parameters used for indieweb identity. You should set these along
  # with the above email/social network parameters.
  [params.indieWeb]  
    EmailAddress = "braxton@cmdcentral.xyz"
    GitHubUser = "bjschafer"
    TwitterUser = "bronxasaur"
    Country = "USA"
    City = "Somewhere"
