baseURL: "https://letstry.science"
languageCode: "en-us"
title: "Snippets of Nifty"
copyright: "Copyright © 2019-2024, Braxton Schafer"
theme: ["gitlab.com/gabmus/hugo-ficurinia"]

security:
  gotemplates:
    allowActionJSTmpl: true # TODO fix

permalinks:
  posts: /:year/:month/:slug/
  page: /:slug/

params:
  author: "Braxton Schafer"
  description: "Snippets of Nifty"
  keywords: "tech howto guide woodworking music"
  email: "braxton@cmdcentral.xyz"

  paperCards: true
  buttonTags: true
  bigArticleTitle: true
  gridView: true
  navtype: "circles"
  menuStyle: "buttons"
  inputStyle: buttons
  showPostsLink: false

  enableShareOnFediverse: true

  faviconIco: "/favicon.ico"
  favicon: "/favicon.png"
  logo: "/logo.png"
  appletouch: "/apple-touch-icon.png"
  icon512: "/icon512.png"

menu:
  main:
    - identifier: about
      name: About
      url: /about/me
      weight: -6
    - identifier: portfolio
      name: Portfolio
      url: https://bjschafer.com
      weight: 110
  icons:
    #    - identifier: gnome
    #      name: BlueSky
    #      url: https://bsky.app/profile/whizkid.dev
    #      weight: -4
    - identifier: github
      name: GitHub
      url: https://github.com/bjschafer
      weight: -4
    - identifier: linkedin
      name: LinkedIn
      url: https://linkedin.com/in/bjschafer
      weight: -3
    - identifier: mastodon
      name: Mastodon
      url: https://mastodon.online/@bronxasaur
      weight: -2
    - identifier: twitter
      name: Twitter
      url: https://twitter.com/bronxasaur
      weight:
        -1

        #[menu]
        #
        #
        #  [[menu.main]]
        #    name: "GitHub"
        #    pre: "<i class='fab fa-github'></i>"
        #    url: "https://github.com/bjschafer"
        #    weight: -3
        #
        #  [[menu.main]]
        #    name: "Mastodon"
        #    pre: "<i class='fab fa-mastodon'></i>"
        #    url: "https://mastodon.online/@bronxasaur"
        #    post: "me"
        #    weight: -2
        #
        #  [[menu.main]]
        #    name: "Twitter"
        #    pre: "<i class='fab fa-twitter'></i>"
        #    url: "https://twitter.com/bronxasaur"
        #    weight: -1
        #
        #  [[menu.main]]
        #    name: "Portfolio"
        #    pre: "<i class='fas fa-briefcase'></i>"
        #    url: "https://bjschafer.com"
        #    weight: 110
